services:
  - type: web
    name: library-management
    env: node
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: php artisan serve --host=0.0.0.0 --port=$PORT
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://library-management.onrender.com 